# Generated by Django 5.2 on 2025-04-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('perfil_id', models.IntegerField(primary_key=True, serialize=False)),
                ('perfil_nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'perfiles',
            },
        ),
    ]
