# Generated by Django 5.2 on 2025-04-29 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanalCliente',
            fields=[
                ('articulo_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nombre_canal', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'canal_cliente',
            },
        ),
        migrations.CreateModel(
            name='GrupoArticulo',
            fields=[
                ('grupo_id', models.UUIDField(primary_key=True, serialize=False)),
                ('codigo_grupo', models.CharField(max_length=5)),
                ('nombre_grupo', models.CharField(max_length=150)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
            ],
            options={
                'db_table': 'grupos_articulos',
                'ordering': ['codigo_grupo'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.UUIDField(primary_key=True, serialize=False)),
                ('tipo_identificacion', models.CharField(max_length=1)),
                ('nro_identificacion', models.CharField(max_length=11)),
                ('nombres', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('correo_electronico', models.CharField(max_length=255)),
                ('nro_movil', models.CharField(max_length=15)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cliente_canal', to='core.canalcliente')),
            ],
            options={
                'db_table': 'cliente',
                'ordering': ['nombres'],
            },
        ),
        migrations.CreateModel(
            name='LineaArticulo',
            fields=[
                ('linea_id', models.UUIDField(primary_key=True, serialize=False)),
                ('codigo_linea', models.CharField(max_length=10)),
                ('nombre_linea', models.CharField(max_length=150)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='grupo_linea', to='core.grupoarticulo')),
            ],
            options={
                'db_table': 'lineas_articulos',
                'ordering': ['codigo_linea'],
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('articulo_id', models.UUIDField(primary_key=True, serialize=False)),
                ('codigo_articulo', models.CharField(max_length=25)),
                ('codigo_barras', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=150)),
                ('presentacion', models.CharField(max_length=100)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('stock', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imagen', models.CharField(max_length=255)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='articulo_grupo', to='core.grupoarticulo')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='articulo_linea', to='core.lineaarticulo')),
            ],
            options={
                'db_table': 'articulos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_id', models.UUIDField(primary_key=True, serialize=False)),
                ('nro_pedido', models.IntegerField()),
                ('fecha_pedido', models.DateTimeField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pedido_cliente', to='core.cliente')),
            ],
            options={
                'db_table': 'pedido',
                'ordering': ['nro_pedido'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('item_id', models.UUIDField(primary_key=True, serialize=False)),
                ('nro_item', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_item', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='item_articulo', to='core.articulo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='item_pedido', to='core.pedido')),
            ],
            options={
                'db_table': 'item_pedido',
                'ordering': ['nro_item'],
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('precio_id', models.UUIDField(primary_key=True, serialize=False)),
                ('precio_1', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_2', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_3', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_4', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='precio_articulo', to='core.articulo')),
            ],
            options={
                'db_table': 'precio',
            },
        ),
    ]
